import React, { Fragment } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Button from "@/components/Buttons";
import Image from "next/image";
import useSWR from "swr";
import styles from "./WorshopPage.module.css";

export default function WorkshopDetailsPage() {
  const router = useRouter();
  const { isReady } = router;
  const { id } = router.query;
  const { data: workshop, isLoading, error } = useSWR(`/api/workshops/${id}`);

  if (!isReady || !workshop || isLoading || error) return <h2>Loading...</h2>;

  return (
    <>
      <Head>
        <title>F. Abdoui Mohamed</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.frame}`}>
        <div className={`${styles.navbox}`}>
          <Button className={`${styles.navButton__workshopButton}`}>
            <Link href="../" className="navLink">
              Home
            </Link>
          </Button>
          <Button className={`${styles.navButton__workshopButton}`}>
            <Link href="/workshops" className="navLink">
              Workshops
            </Link>
          </Button>
          <Button className={`${styles.navButton__bookingButton}`}>
            <Link href="/booking" className="navLink">
              Booking
            </Link>
          </Button>
          <Button className={`${styles.navButton__mediaButton}`}>
            <Link href="/media" className="navLink">
              Media
            </Link>
          </Button>
        </div>
        {workshop.images.map((image) => {
          return (
            <Fragment key={image.id}>
              <div className={`${styles.imagebox} ${styles.overlappingImage1}`}>
                <Image
                  src={image.url}
                  alt="Picture"
                  className={`${styles.homeImage}`}
                  fill={true}
                />
              </div>
            </Fragment>
          );
        })}
        <h6>{workshop.titleEnglish}</h6>
        <p>{workshop.textEnglish}</p>
      </main>
    </>
  );
}
