import React, { Fragment } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import Image from "next/image";
import Quote from "@/components/Quote";
import useSWR from "swr";
import styles from "./WorshopPage.module.css";

export default function WorkshopPage() {
  const router = useRouter();
  const { data: workshops, isLoading } = useSWR("../api/workshops/");
  if (isLoading) {
    return <h1>Loading...</h1>;
  }

  if (!workshops) {
    return <h4>sorry, image cannot be loaded</h4>;
  }
  console.log("workshops", workshops);

  //   const imageWS1 = images.find((img) => (img.image = "File_24_v9z1nk"));
  //   console.log("imageWS1", imageWS1);
  //   const overlapImageWS1 = images.find(
  //     (image) => (image.image = "File_32_vqnmat")
  //   );
  //   const imageWS2 = images.find((image) => (image.image = "File_15_lrzamh"));
  //   const imageWS3 = images.find((image) => (image.image = "File_26_qkfli3"));
  //   const imageWS4 = images.find((image) => (image.image = "File_23_dofm39"));
  //   const imageWS5 = images.find((image) => (image.image = "File_29_whvhcm"));

  return (
    <>
      <Head>
        <title>F. Abdoui Mohamed</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.frame}`}>
        <div className={`${styles.navbox}`}>
          <Button className={`${styles.navButton__workshopButton}`}>
            <Link href="/workshops" className="navLink">
              Workshops
            </Link>
          </Button>
          <Button className={`${styles.navButton__bookingButton}`}>
            <Link href="/booking" className="navLink">
              Booking
            </Link>
          </Button>
          <Button className={`${styles.navButton__mediaButton}`}>
            <Link href="/media" className="navLink">
              Media
            </Link>
          </Button>
        </div>
        <Quote />
        {workshops.map((workshop) => {
          return (
            <Fragment key={workshop._id}>
              {workshop.images.map((image) => {
                return (
                  <Fragment key={image.id}>
                    <div
                      className={`${styles.imagebox} ${styles.overlappingImage1}`}
                    >
                      <Image
                        src={image.url}
                        // src={
                        //   "https://res.cloudinary.com/dkrguoage/image/upload/v1697711589/Workshop%20Bilder/File_24_v9z1nk.webp"
                        // }
                        alt="Picture"
                        className={`${styles.homeImage}`}
                        fill={true}
                      />
                    </div>
                  </Fragment>
                );
              })}
              <h6>{workshop.titleEnglish}</h6>
              <p>{workshop.textEnglish}</p>
            </Fragment>
          );
        })}
        <div className={`${styles.imagebox}`}>
          <Image
            //src={imageWS2.url}
            src="https://res.cloudinary.com/dkrguoage/image/upload/v1697711747/Workshop%20Bilder/File_15_lrzamh.jpg"
            alt="Picture"
            className={`${styles.homeImage}`}
            fill={true}
          />
        </div>
        <div className={`${styles.imagebox}`}>
          <Image
            //src={imageWS3.url}
            src="https://res.cloudinary.com/dkrguoage/image/upload/v1697711220/Workshop%20Bilder/File_26_qkfli3.jpg"
            alt="Picture"
            className={`${styles.homeImage}`}
            fill={true}
          />
        </div>
        <div className={`${styles.imagebox}`}>
          <Image
            //src={imageWS4.url}
            src="https://res.cloudinary.com/dkrguoage/image/upload/v1697711871/Workshop%20Bilder/File_23_dofm39.webp"
            alt="Picture"
            className={`${styles.homeImage}`}
            fill={true}
          />
        </div>
        <div className={`${styles.imagebox}`}>
          <Image
            //src={imageWS5.url}
            src="https://res.cloudinary.com/dkrguoage/image/upload/v1697711744/Workshop%20Bilder/File_29_whvhcm.jpg"
            alt="Picture"
            className={`${styles.homeImage}`}
            fill={true}
          />
        </div>
      </main>
    </>
  );
}
