import React, { Fragment } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Button from "@/components/Buttons";
import Image from "next/image";
import Quote from "@/components/Quote";
import useSWR from "swr";
import styles from "./WorshopPage.module.css";

export default function WorkshopPage({ inEnglish }) {
  const router = useRouter();
  const { data: workshops, isLoading } = useSWR("../api/workshops/");
  if (isLoading) {
    return <h1>Loading...</h1>;
  }

  if (!workshops) {
    return <h4>sorry, page cannot be loaded</h4>;
  }
  console.log("workshops", workshops);

  //   const imageWS1 = images.find((img) => (img.image = "File_24_v9z1nk"));
  //   console.log("imageWS1", imageWS1);
  //   const overlapImageWS1 = images.find(
  //     (image) => (image.image = "File_32_vqnmat")
  //   );
  //   const imageWS2 = images.find((image) => (image.image = "File_15_lrzamh"));
  //   const imageWS3 = images.find((image) => (image.image = "File_26_qkfli3"));
  //   const imageWS4 = images.find((image) => (image.image = "File_23_dofm39"));
  //   const imageWS5 = images.find((image) => (image.image = "File_29_whvhcm"));

  return (
    <>
      <Head>
        <title>F. Abdoui Mohamed</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.frame}`}>
        <Link className={`${styles.stickyLink_Home}`} href="/">
          <button className={`${styles.navButton} ${styles.homeButton}`}>
            Home
          </button>
        </Link>
        <Link className={`${styles.stickyLink_Booking}`} href="/booking">
          <button className={`${styles.navButton} ${styles.bookingButton}`}>
            Booking
          </button>
        </Link>
        <Link className={`${styles.stickyLink_Media}`} href="/media">
          <button className={`${styles.navButton} ${styles.mediaButton}`}>
            {inEnglish ? "Media" : "Medien"}
          </button>
        </Link>
        {workshops.map((workshop) => {
          return (
            <div key={workshop._id} className={`${styles.workshopContainer}`}>
              <Link href={`/workshops/${workshop._id}`}>
                {workshop.images.map((image) => {
                  return (
                    <Fragment key={image._id}>
                      <div className={`${styles.imagebox}`}>
                        <Image
                          src={image.url}
                          alt="Picture"
                          className={`${styles.homeImage}`}
                          fill={true}
                        />
                      </div>
                    </Fragment>
                  );
                })}
                {/* <div className={`${styles.workshoptitleContainer}`}> */}
                <h6 className={`${styles.workshoptitle}`}>
                  {inEnglish ? workshop.titleEnglish : workshop.titleGerman}
                </h6>
                {/* </div> */}
              </Link>
            </div>
          );
        })}
      </main>
    </>
  );
}
